### ISSUE TITLE
Delete a job by updating state

### ISSUE THREAD

**Issue by reidwil-jb** [data-mie/dbt-cloud-cli#24]
According the [api docs](https://docs.getdbt.com/dbt-cloud/api-v2#operation/updateJobById) you can update a job to be "deleted" by changing the state of the job from 1 to 2. This might be the correct approach to deleting a job as opposed to sending a delete request.

https://github.com/data-mie/dbt-cloud-cli/blob/eaac8489a6ad10fada216da2fa989105bd2ba4a5/dbt_cloud/command/job/delete.py#L21

**Comment by iktl** [comment]
Hi @reidwil-jb! I'm on the Platform team at dbt Labs, both should work equivalently here.

The `DELETE` HTTP handler on pretty much every endpoint just flips `state` behind the scenes. You could also 100%, on this endpoint, "delete" a record as you say by flipping `state` yourself since we soft-delete almost everything.

I think one argument to tip toward favouring `DELETE` outright is that it lets us (dbt Labs) determine whether deleting means state-flipping or outright record deletion (rare), per endpoint, and doesn't require an API consumer like this repository to understand those implementation details.

**Comment by stumelius** [comment]
@reidwil-jb I hadn't realized that jobs can be deleted by state-flipping! And thanks for your input @reidwil-jb , I think we'll stick with the `DELETE` approach unless there are some other implications to using `DELETE` vs state-flipping that haven't been considered?

**Comment by reidwil-jb** [comment]
@iktl Thank you for weighing in! I'm happy to be wrong here. Learned something new!

**Comment by reidwil-jb** [comment]
@iktl - Revisiting this, I tried sending a delete request to a specific job's endpoint and it successfully deleted. In this instance, if I were to not capture the context of the job, how would I be able to bring it back if I hypothetically wanted to "undelete" the job?

**Comment by iktl** [comment]
That's a fair question @reidwil-jb — if retaining the context is important, it's probably better to send the `POST` request and flip the state so you can reactivate it later. I'd consider this an unintended benefit of us exposing state publicly and probably isn't something to rely on in v4 as we build that out in the future.
